### PR TITLE
Add ability to Test feeds and AJAX load the log when doing manual pull

### PR DESCRIPTION
**Pull request by sc0ttkclark**
On clicking of Manual pull, it now AJAX refreshes the log meta box with the latest from the manual pull.

I also fixed an issue with the meta box #fp_manual_pull that the JS was targeting unintentionally for the button with the same ID. Changed button ID to #fp_manual_pull_run

To be able to do all this, I had to abstract the feed fetching functionality into it's own `get_feed_posts` method and give it public access. `do_pull` still has private access and utilizes this new abstracted method just fine.

The constructor now accepts a false, and if false it will not run `do_pull` (null still runs all feeds).

This does not send the current feed settings from the form, it still requires saving, just like Do Feed Pull. I chose not to change that functionality there.

I saw there was a string with the wrong text domain in it called `my-reviews`.

screen shot 2015-01-30 at 10 25 10 pm

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Follow up for better error handling, right now the white-space: pre doesn't look good for errors/warnings because it's HTML passed back. JS could check for an error via `.match()` but I'm not 100% sure how best to handle that at the moment. Open to thoughts. We could probably check if data.success is false and toggle between `.css( 'white-space', '' )` and `.css( 'white-space', 'pre' )`

**Comment by tlovett1** [comment]
Anything else worth explaining here? It's super hard to tell what's been moved and what is new/changed.

**Comment by sc0ttkclark** [comment]
* I abstracted fp_fetch_feed into FP_Pull
* I abstracted the feed item fetch from do_pull into get_feed_items
* I abstracted the feed item field mapping from do_pull into get_feed_posts (calls get_feed_items)
* I cleaned up do_pull for the purpose of abstracting the above two items (calls get_feed_posts, which calls get_feed_items)
* I added AJAX callback for testing feed pull that returns the first full mapped feed post array (post fields, post meta, taxonomy fields) (including the JS needed for that)
* I added AJAX display of log from manual feed pull into meta box for the Feed Log
* I added a check in AJAX feed pull to bail on feed pull and throw a notice if the feed is not published

The fetch items / posts abstraction required moving a bit of code around to consolidate logic vs save and make it easier to eventually add additional tests for some more extensive testing via unit tests.

**Comment by sc0ttkclark** [comment]
Word.

**Pull request merged**
